Fix #1032: Workspace doesn't bump hard enough when swiping at the end
elementary/gala pull request #1036
Opened 2021-01-31 11:40 UTC by JoseExposito

Fix https://github.com/elementary/gala/issues/1032

2021-02-06 09:37 UTC, jlnr commented on src/WindowManager.vala
> +         * If using a touchpad or touchscreen the animation is smaller that using the keyboard. This
Typo?
```suggestion
         * If using a touchpad or touchscreen the animation is smaller than using the keyboard. This
```

2021-02-06 09:45 UTC, JoseExposito commented on src/WindowManager.vala
> +         * If using a touchpad or touchscreen the animation is smaller that using the keyboard. This
Yep

2021-02-23 23:59 UTC, danrabbit requested changes
Hrm this seems really arbitrary and I don't think really solves the issue. This would make the nudge much large sometimes and still smaller sometimes. It wouldn't make the two nudges uniform.

When you start a workspace switch, the minimum distance the workspace is moved when the gesture is accepted is about the distance of the workspace gap, but when you start a nudge, the minimum distance is just a few pixels. So if you're swiping quickly, even with this branch you might only move 6px or so and the nudge animation is barely noticeable.

2021-02-25 19:15 UTC, JoseExposito commented
> When you start a workspace switch, the minimum distance the workspace is moved when the gesture is accepted is about the distance of the workspace gap, but when you start a nudge, the minimum distance is just a few pixels. So if you're swiping quickly, even with this branch you might only move 6px or so and the nudge animation is barely noticeable.

Aham, now I understand what solution you want.

So, when you switch workspaces, the 100% of the movement in your touchpad matched the size of your screen.
However, in the nudge animation that 100% of movement matches 32 pixels.
I just pushed some changes so both animation are identical with the exception than the nudge animation ends at 32px.

Even though this is the "coherent" way of handling this animation it feels a little bit rough...

2021-03-01 14:26 UTC, hanaral commented
I've already filed feature request for  - But I was wondering how difficult it would be to make the workspace bump a part of the animation before it i.e. swiping from workspace 2 to workspace 1 and continuing to pull would animate the stretch

2021-03-01 17:30 UTC, JoseExposito commented
> I've already filed feature request for it - But I was wondering how difficult it would be to make this workspace bump a part of the animation before it i.e. swiping from workspace 2 to workspace 1 and continuing to pull would animate the stretch

I'm afraid that at the moment that'll require few changes... We'll need to handle that extra swipe movement and also change how the animation is performed drastically as, under the hood, only the current desktop + windows and the target desktop + windows are drawn.
It's possible, but it'll require a lot of work. By the way, feel free to mention me in a issue if you want to ask a question, I don't check the issue tracker that often :smile:

2021-04-02 17:48 UTC, danrabbit commented
can confirm, this branch bumps :sunglasses:

2021-04-04 11:27 UTC, JoseExposito commented
@danrabbit I rebased the changes in 3 commits so the change is easier to follow

2021-04-05 16:47 UTC, danrabbit approved these changes

2021-04-05 17:08 UTC, merged