WindowManager: dim parents of modals
elementary/gala pull request #1285
Opened 2021-11-02 19:28 UTC by danrabbit

Fixes #576

2021-11-02 21:55 UTC, cassidyjames requested changes
This seems like a good start, but I am seeing some strange behavior when moving windows: if you open a modal window and then try to move the parent, the child ends up shooting off the right side of the display.

2021-11-02 21:55 UTC, danrabbit commented
@cassidyjames that also happens in master

2021-11-02 21:59 UTC, cassidyjames commented
@danrabbit lmao oh that's nasty. Alright, confirmed and filed as #1286

2021-11-04 08:26 UTC, JoseExposito requested changes
Just a little comment about the code.

The effect looks nice, but I feel like it's too sudden. Maybe we could animate it for a short period of time.

GNOME Shell has a good (JavaScript) example to follow.

2021-11-04 08:26 UTC, JoseExposito commented on src/WindowManager.vala
> -        public void dim_window (Meta.Window window, bool dim) {
I think it'd be a good idea to keep this method around and move the logic to dim/"un-dim" an actor here.

2021-11-05 21:29 UTC, danrabbit commented
@JoseExposito pushed the method, but I don't think I'm familiar enough with clutter to be able to implement the animation. Would love help :sweat_smile:

2021-11-06 09:18 UTC, JoseExposito approved these changes
Code looks much nicer.

@danrabbit here GNOME's implementation:
https://github.com/GNOME/gnome-shell/blob/483d1b3177a8b35599b5825b4ac51a105b360c08/js/ui/windowManager.js#L125

On the surface, it looks simple, but things will get complicated to migrate their `ease_property` method:
https://github.com/GNOME/gnome-shell/blob/cc5cc0d653ccd307475921bf069773d44b34aa5e/js/ui/environment.js#L223

In my opinion we can merge this as it is and add the animation in the future. Feel free to press the merge button :)

2021-11-06 17:00 UTC, merged