Remove corner mask in favor of rounded background corners
elementary/gala pull request #1846
Opened 2024-02-08 21:25 UTC by leolost2605

By making the system background entirely black we can remove the maskcorners plugin since we already round the background corners.

The only difference is that now windows or anything that's in the corner doesn't get rounded so I guess that's a design question 🤷

2024-02-08 21:40 UTC, danirabbit approved these changes
So the only place you notice this afaict is like fullscreen apps. Which I'm fine with fullscreen apps figuring out their own corners. This looks good to me! I'm happy if @lenemter is happy :)

2024-02-08 21:54 UTC, lenemter requested changes
You also need to deprecate the gsettings keys the plugin used

2024-02-08 23:51 UTC, leolost2605 commented
@lenemter done!

2024-02-09 09:24 UTC, lenemter commented
For some reason windows are still getting clipped at corners and corners stay black even if I change background color to the old gray one. So nothing has changed for me.

@leolost2605 Could you revert the change to the background color please? The color is still shown when switching workspaces and black looks bad here.

2024-02-09 10:10 UTC, leolost2605 commented
> For some reason windows are still getting clipped at corners and corners stay black even if I change background color to the old gray one. So nothing has changed for me.

I think that's because the plugin isn't actually uninstalled when you install the branch so it's still there. I tested it by disabling the plugin 🤷

> @leolost2605 Could you revert the change to the background color please? The color is still shown when switching workspaces and black looks bad here.

Ah right I almost thought I might have missed a use :) Will change it

2024-02-10 14:10 UTC, leolost2605 commented
@lenemter this should be fixed now :)

2024-02-10 14:23 UTC, lenemter requested changes
Nice! Using `background_color` is a good solution but now the black corners are visible during workspace switch animation. To fix this you can change their color to transparent.

2024-02-10 14:39 UTC, leolost2605 commented
You mean by workspace switch switch via touchpad swipe/super + left/right? 
Because they aren't black for me there 🤔

2024-02-10 14:45 UTC, lenemter commented
@leolost2605 Yes

![screenshot](https://github.com/elementary/gala/assets/80143868/44c0989a-466f-4513-a87c-30d4e05deb10)

It's more obvious if I change system bg to white:

![screenshot white](https://github.com/elementary/gala/assets/80143868/50b55e34-b2de-4e73-ba25-0f787f669a68)

2024-02-10 15:44 UTC, leolost2605 commented
@lenemter ok so I'm guessing this has something to do with whether you have workspaces on primary only. Btw how do I disable this cause I didn't find it anywhere? Is there a dconf key somewhere?

I pushed your mentioned fix, couldn't test it though. Also if you have a better name for the method just change it I just couldn't figure out a  good name :)

2024-02-10 15:46 UTC, lenemter commented
@leolost2605 it's /org/gnome/mutter/workspaces-only-on-primary. I don't have second monitor, so I don't know how it would affect it

2024-02-10 15:48 UTC, lenemter commented
@leolost2605 it crashes wm for me

```
(gdb) bt
#0  0x000055e194671399 in gala_background_container_black_background (self=0x55e1959408f0, black=0)
    at ../src/Background/BackgroundContainer.vala:52
#1  0x000055e194659a1a in gala_window_manager_gala_prepare_workspace_switch (self=0x55e19593b250, from=0, to=1, direction=META_MOTION_RIGHT)
    at ../src/WindowManager.vala:1941
#2  0x000055e19465c64a in gala_window_manager_gala_real_switch_workspace (base=0x55e19593b250, from=0, to=1, direction=META_MOTION_RIGHT)
    at ../src/WindowManager.vala:2121
#3  0x00007fc62b2f35d9 in meta_workspace_activate_with_focus (workspace=0x55e195596cd0, focus_this=0x0, timestamp=0)
    at ../src/core/workspace.c:684
#4  0x000055e19464d5c8 in gala_window_manager_gala_real_switch_to_next_workspace
    (base=0x55e19593b250, direction=META_MOTION_RIGHT, timestamp=0) at ../src/WindowManager.vala:594
#5  0x00007fc62c452bf3 in gala_window_manager_switch_to_next_workspace (self=0x55e19593b250, direction=META_MOTION_RIGHT, timestamp=0)
    at ../lib/WindowManager.vala:183
```

2024-02-10 15:54 UTC, leolost2605 commented
@lenemter IIUC if workspaces_on_primary_only is enabled the workspace switch only uses the backgroundmanager of the primary/only monitor. But if it's disabled it uses the whole backgroundcontainer (where the black background is set) no matter whether you have one or multiple monitors.

Also the crash should be fixed now

2024-02-10 15:59 UTC, lenemter reviewed
Looks very good. One last comment

2024-02-10 15:59 UTC, lenemter commented on src/Background/BackgroundContainer.vala
> +        public void black_background (bool black) {
Method names usually use verbs. Rename this to `set_black_background` please :)

2024-02-10 16:02 UTC, leolost2605 commented
Done!

Btw is workspaces on all monitors something we might want to support in the future? Because currently it's entirely broken with multiple monitors?

2024-02-10 16:03 UTC, lenemter approved these changes
:rocket:

2024-02-10 16:03 UTC, merged

2024-02-10 16:07 UTC, lenemter commented
@leolost2605 Personally, I'd like to add support for https://github.com/elementary/gala/issues/26 when/if mutter implements this, and don't find workspaces on all monitors useful. Maybe @danirabbit has an opinion on this?