Introduce a wayland/x11 mutter hints protocol for monitor labels
elementary/gala pull request #2084
Opened 2024-10-12 11:24 UTC by leolost2605

Currently we do monitor labels quite awkard. First the display plug has to go via dbus to the daemon having to send a lot of stuff, like color info, monitor index, label, x, y then the daemon spawns the labels and then gala looks at the window title and positions the label.

This can be made properly now by just using a wayland protocol/ setting the mutter hints on x11.

This will allow us to drop the GTK3 daemon with some more fine tuning to the menus so that's left to another PR.

This also includes some cleanup of the positioning logic for the shellclients by introducing a WindowPositioner which is used for both centered windows and monitor labels. That also fixes an issue that caused centered windows to sometimes not be centered.

2024-10-12 16:51 UTC, danirabbit requested changes, later dismissed
Since we're in the stable release phase we can add new API but we can't break old API until the next major version bump

2024-10-13 17:05 UTC, leolost2605 commented
Ah right that is a thing oops :sweat_smile: 
This isn't very important just a better and slightly improved way to do it so it's obviously fine to wait
I think I'll factor out the WindowPositioner and the corresponding fix for centered windows though and prepare a separate PR for that (which, TBH, it probably should be anyway)

2025-02-03 06:19 UTC, danirabbit commented
@leolost2605 is it possible to add the new API without breaking the old API so we can move forward?

2025-11-07 20:54 UTC, leolost2605 commented
@danirabbit finally got around to updating this so it should be ready without breaking the current API :)

2026-04-20 17:27 UTC, zeebok approved these changes
I dunno what was here before that was breaking API but _this_ code looks good to me

2026-04-21 16:12 UTC, lenemter approved these changes

2026-04-22 12:26 UTC, merged