Shortcuts: Add an interactive screenshot shortcut
elementary/gala pull request #2125
Opened 2024-11-24 17:14 UTC by leolost2605

Add a keyboard shortcut to launch the screenshot app.
Default is `Super` + `Print`

This is useful as an alternative to having to remember all of the shortcuts for screen, window, area and their clipboard variants or just in general if you prefer the interactive way.
As a bonus it also has the save dialog.
(As prior art: e.g. GNOME launches its interactive UI by default for the Print key, windows has snipping tool, etc.)

Needs to be added to the keyboard plug

2024-11-24 19:33 UTC, stsdc commented
![obraz](https://github.com/user-attachments/assets/48b67ef7-c04f-4e86-a004-835d47e93c2f)
I have this `super + Q`  to screenshot an area to clipboard.

2024-11-24 19:34 UTC, stsdc approved these changes

2024-11-24 19:41 UTC, lenemter commented
Please do not merge this. I'd really like to release 8.0.4 as a hotfux before the OS 8 release

2024-12-03 17:16 UTC, lenemter requested changes
It doesn't work on OS 8. Screenshot is flatpak here.

1. You should change it to `flatpak run io.elementary.screenshot`
2. Maybe make command editable? Some user might want to use different screenshot tool and IMO we shouldn't hardcode it.

2024-12-03 17:44 UTC, leolost2605 commented
Updated it :)

2024-12-03 17:52 UTC, lenemter approved these changes
Looks great and works as intended :tada:

2024-12-03 17:54 UTC, merged