Wayland: start gnome-session-x11-services-ready.target
elementary/gala pull request #2140
Opened 2024-12-03 21:05 UTC by lenemter

Fixes https://github.com/elementary/gala/issues/1967
Fixes https://github.com/elementary/gala/issues/2113
Fixes https://github.com/elementary/gala/issues/2131

2024-12-03 22:00 UTC, leolost2605 requested changes
Only some minor comments apart from that makes sense to me but I don't really know the inner workings here :)

2024-12-04 02:35 UTC, vjr reviewed
I can confirm it fixes at least #1967 for me!

2024-12-04 02:37 UTC, vjr approved these changes

2024-12-04 02:46 UTC, vjr commented
@lenemter just wondering whether instead of doing this in code is it not possible/advisable to configure this systemd service/unit to start via the config files?

2024-12-04 10:00 UTC, lenemter commented
@vjr gnome shell does it this way, I think they know how to do this better than me :)

2024-12-04 10:04 UTC, lenemter commented on src/WindowManager.vala
> +                session_bus.call.begin (
Done!

2024-12-04 10:04 UTC, lenemter commented on src/WindowManager.vala
> +                var session_bus = GLib.Bus.get_sync (GLib.BusType.SESSION);
Fixed

2024-12-04 15:17 UTC, merged