MultitaskingView: Allow workspace switch gesture to be interrupted
elementary/gala pull request #2161
Opened 2024-12-11 23:05 UTC by leolost2605

First step towards #1202 

Remaining are multitasking view open and close and while on the desktop workspace switch but those require the cancelling fixes and are left to follow up PRs.

2024-12-19 20:24 UTC, lenemter requested changes
This branch is bugged after merging https://github.com/elementary/gala/pull/2164 :/

2024-12-19 23:45 UTC, leolost2605 commented
@lenemter can you describe what happens? It seems to work fine for me :/

2024-12-20 13:48 UTC, lenemter commented
This bug happens when you interrupt workspace switch animation while switching to the last workspace

https://github.com/user-attachments/assets/9aa24538-5639-4ac5-a2e5-360b2c5afa37

2025-01-25 14:41 UTC, leolost2605 commented
This should be ready now. 
Cancelling is now also much more predictably. We cancel if
- We haven't moved far enough and our velocity is to low
- We are going backwards with enough velocity

This fixes some unintuitive behavior like when switching to a new workspace and you're already there but you decide to go back and swipe fast backwards it won't cancel.

2025-01-25 15:32 UTC, leolost2605 commented
I just realized this somehow cancels multitasking view open/close even though it shouldn't...
I'll look into it :)

2025-01-25 15:50 UTC, leolost2605 commented
Ok it's fixed now so ready again :)

2025-01-25 16:16 UTC, lenemter approved these changes
This looks weird with touchegg backend but there's nothing we can do with it. Looking forward using this with touchpad backend

2025-01-25 16:17 UTC, merged