Add Super+Scroll actions
elementary/gala pull request #2165
Opened 2024-12-13 14:02 UTC by lenemter

Fixes https://github.com/elementary/gala/issues/815
Fixes https://github.com/elementary/gala/issues/1178

2024-12-13 14:29 UTC, leolost2605 requested changes
I really really love this!

2024-12-13 14:29 UTC, leolost2605 commented on src/WindowManager.vala
> +            stage.add_action_full ("super-scroll-action", CAPTURE, scroll_action);
Currently all of the stage stuff and keybindings etc. is done in show_stage maybe we should do this there as well?

2024-12-14 20:20 UTC, leolost2605 reviewed
On second thought I think it might be better to make the `void triggered ()` signal a `bool triggered ()`, return that for propagation and have everything that needs a super scroll action add their own. This would stay more in line with how events, etc. are generally handled and avoids having to add even more api to the windowmanager.
What do you think?

2024-12-19 13:39 UTC, leolost2605 commented
> @leolost2605 we need to implement our own objects hierarchy for this to make sense

I'm not sure I understand what you mean here?

2024-12-19 15:28 UTC, lenemter commented
How are we gonna propagate the signal in this case? It's not an event, so we can't use Clutter... TBH I don't understand exactly what you mean in your original comment.

2024-12-19 17:44 UTC, leolost2605 commented
I meant something like the last commit in #2182 does

2024-12-19 20:33 UTC, closed without merging