ShellClients: Use translation y instead of clone and gesturetransition for animation
elementary/gala pull request #2192
Opened 2024-12-24 11:20 UTC by leolost2605

Split out from #2150 for easier review.

This introduces some inconsistencies when opening multitasking view and switching workspaces but these will be fixed properly by the follow ups from #2150.

The changes here include using the translation-y property of the window actor to hide it instead of making it invisible and animating a clone. Also included is the use of the GesturePropertyTransition for the actual animation and the related introduction of GestureTrackers. This is preparation for moving all panel hiding stuff to the shell clients (instead of the multitasking view doing its own thing with additional clones) as well as one to one touch gestures for showing the dock.

2024-12-24 11:40 UTC, lenemter commented on src/ShellClients/HideTracker.vala
Can't we use `default_gesture_tracker` instead of passing gesture_tracker into update_overlap and update_hidden?

2024-12-24 11:41 UTC, lenemter commented on src/ShellClients/PanelClone.vala
> +        if (!panel_hidden || last_gesture_tracker.recognizing) {
same here, PanelClone already has default_gesture_tracker, why do we pass it here again?

2024-12-25 20:17 UTC, leolost2605 commented
@lenemter ok I've removed the gesturetracker passing from this commit so that it will make more sense in the commit history where we'll introduce it once we actually need it :)

2025-01-05 14:36 UTC, lenemter commented on src/ShellClients/PanelClone.vala
> +    private float calculate_y (bool hidden) {
I think 'calculate_y' is ambiguous in this case because it calculates translation not coordinates, maybe 'calculate_translation_y' would be better?

2025-01-13 22:26 UTC, leolost2605 commented on src/ShellClients/PanelClone.vala
> +    private float calculate_y (bool hidden) {
Updated it :)

2025-01-13 22:44 UTC, lenemter requested changes
I can partially reproduce https://github.com/elementary/gala/issues/2080. After starting the session open a new maximized window, the dock windows are placed behind said window. Probably requires same workaround as https://github.com/elementary/gala/pull/2094?

2025-01-13 22:48 UTC, leolost2605 commented
@lenemter that will be completely fixed by #2195 
Would it be ok if we just merge this and then get #2195 in as well?

2025-01-13 22:52 UTC, lenemter approved these changes
:rocket:

2025-01-13 22:53 UTC, merged