Introduce a shell group
elementary/gala pull request #2195
Opened 2024-12-25 21:07 UTC by leolost2605

Since moving the panel hiding from the multitasking view completely to the shell clients and introducing a shell group are bigger changes, I think they probably should be separated which is what this PR does.

It still includes the new version of #2192 but now only introduces the shell group which is (taken from the code comment):

> The group that contains all WindowActors that make shell elements, that is all windows reported as 
ShellClientsManager.is_positioned_window and notifications, as well as manually added elements.
         It will (eventually) never be hidden by other components and is always on top of everything. Therefore elements are
         responsible themselves for hiding depending on the state we are currently in (e.g. normal desktop, open multitasking view, fullscreen, etc.).

This will allow us to fix https://github.com/elementary/gala/issues/2130, have wingpanel and dock interactable in the windowoverview (currently they show but you can't do anything with them) or eventually we can keep e.g. the dock visible and interactable in the multitasking view.

There are no functional changes apart from the side effect that we get a nice hide animation for the panels when entering fullscreen.

2025-01-13 22:27 UTC, leolost2605 commented
There were some minor changes made (renaming) in #2192 that I'm to lazy to replicate here so merge that first and I'll just drop the commit here then :)

2025-01-13 23:03 UTC, lenemter requested changes

2025-01-13 23:03 UTC, lenemter commented on src/InternalUtils.vala
> +                var actor = (Meta.WindowActor) transient.get_compositor_private ();
```suggestion
                unowned var actor = (Meta.WindowActor) transient.get_compositor_private ();
```

2025-01-13 23:03 UTC, lenemter commented on src/ShellClients/PanelClone.vala
> +        wm.shell_group.add_child (actor);
why not use `InternalUtils.clutter_actor_reparent`?

2025-01-13 23:03 UTC, lenemter commented on src/WindowManager.vala
> +                shell_group.add_child (actor);
same here

2025-01-13 23:03 UTC, lenemter commented on src/WindowManager.vala
> +            }
why do we have that here? it looks unrelated to the topic of this PR

2025-01-13 23:18 UTC, leolost2605 commented on src/WindowManager.vala
> +            }
I'm sorry that change was actually a remnant from some testing I did. 
However the other change in end_switch_workspace () is required because now we can actually end up in a situation where windows and their parents is null. However just returning was wrong there (which wasn't noticed previously because we always had wingpanel and dock).

(FYI this will be completely removed in #2225 anyways)

2025-01-17 22:12 UTC, lenemter approved these changes
Code looks good and from my minimal testing works as expected

2025-01-17 22:12 UTC, lenemter commented
CI is failing because of ubuntu repos

2025-01-17 22:15 UTC, merged