Add style transition API
elementary/gala pull request #539
Opened 2019-05-18 00:42 UTC by donadigo

Adds a new method to the DBus API called `transition_from_snapshot` for apps (and primarily the switchboard plug) to be able to create a smooth stylesheet transition. The transition will not happen when animations are disabled but the snapshot will still be created and added (that is it will stay for 200ms and hide without any animations). 

The code should be quite optimized for the task, I previously used a simple `Cogl.Texture.get_data` for creating a static texture but it turned out to be quite long to execute: transferring pixel data from GPU to CPU took ~15ms on my machine which is little bit above 60FPS but there were longer runs that caused visible lag when creating textures for maximized windows. We now copy the texture directly on the GPU which takes about ~2ms.

2019-05-18 00:48 UTC, danrabbit commented
I guess an obvious question is, what about Wayland? Do we get window IDs like this once we move away from X?

2019-05-18 01:02 UTC, donadigo commented
1. No one knows. See https://github.com/elementary/gala/issues/68. I'm not sure if mutter will do anything about this but it seems like there's no standard for those things either. I also don't know how mutter on wayland handles window ID's.

2. We can optionally separate the other part of the method to a new one but it will be still public though.

2019-05-19 02:00 UTC, donadigo commented
@danrabbit updated.

2020-01-24 17:49 UTC, cassidyjames commented
Does this need to be an external API at all? Can't Gala just listen to the setting and do this transition automatically?

2020-01-24 18:02 UTC, donadigo commented
@cassidyjames yeah that and if gala listened to that setting you have to account for the fact that the signal could fire later than the theme change, causing a jarring flick before the actual transition. That's why it's safer to have the app call before actually changing the setting. If we had a Gtk fork / patch then perhaps that would be possible to do automatically.

2020-11-19 01:07 UTC, donadigo commented
Branch updated to use the newest Cogl2 API and updated to master.

2020-11-21 23:43 UTC, donadigo commented
Ready for review again.

2020-11-24 23:47 UTC, danrabbit commented
Hm, I can't really see that this smooths anything out for me. Is there something I need to do other than install this branch and restart my session?

2020-12-03 11:46 UTC, donadigo commented
@danrabbit hm, that's weird. Installing the branch & restarting should be enough. Is the transition like instant, or do you see at least some trace of the animation?

2021-07-17 05:48 UTC, cassidyjames commented on lib/Constants.vala
> +        STYLE_SWITCH = 200
200 would feel nice and snappy, but it seems to not be slow enough to mask all the GTK transitions. Something like 500 seems to mask them better.

```suggestion
        STYLE_SWITCH = 500
```

2021-07-17 05:51 UTC, cassidyjames commented on src/DBus.vala
> +            const uint STYLE_CHANGE_COMPLETION_DURATION = 150;
I've been playing with this, and 300 seems to be long enough to mask WebKit transitioning as well which is a really nice effect.

```suggestion
            const uint STYLE_CHANGE_COMPLETION_DURATION = 300;
```

2021-07-17 05:54 UTC, cassidyjames commented on lib/Constants.vala
> +        STYLE_SWITCH = 200
Oh, nevermind, ignore me. 200 works fine if we increase the delay below slightly.

2021-07-17 05:56 UTC, cassidyjames commented
@donadigo would it be possible to resolve conflicts here? I'm not sure why we weren't seeing it work in the past, but now that we have all the other dark style bits merged in, this would be an incredibly nice effect.

2021-07-25 17:31 UTC, JoseExposito requested changes
I didn't notice there was a PR open with this functionality, definitely something really cool to have! 
It's most likely something related to my set up, but I'm seeing some noise in the panel and shadows:

https://user-images.githubusercontent.com/1335948/126907909-8545c1cd-9f28-4c14-886c-61a7b432f57d.mp4

2024-08-21 17:42 UTC, danirabbit commented
Gonna close this since there was a lot more progress on #1242

2024-08-21 17:42 UTC, closed without merging